title: Nola Musicians for Palestine

exclude: 
  - assets/recordings/src/
  - assets/images/event_flyers/old/
  - assets/images/Workspace/
  - _events/old/


collections:
  events:
  songs:
    output: true


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      type: "songs"
    values:
      layout: "song"
