title: Nola Musicians for Palestine

collections:
  events:
  songs:


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
