FROM python:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        gcc \
        libffi-dev \
        python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install ipython python-frontmatter google-api-python-client google-auth-httplib2 google-auth-oauthlib pytz python-slugify packaging

